# This is the configuration file for the plugin

# MySQL Configuration
mysql:
  host: localhost
  port: 3306
  database: test
  username: root
  password: root

# Only if you want to reset the tables
# It will just delete them. They will be created if they don't exist anyway
# If you want to recreate the tables, set this to true
recreate_tables: false

sync_from_db: false
sync_to_db: true
